trigger:
  branches:
    include:
      - main

stages:
  - stage: BuildAndPush
    displayName: 'Build and Push Docker Image to AWS ECR'
    jobs:
      - job: Build
        displayName: 'Build and Push Job'
        pool:
          vmImage: 'ubuntu-latest'

        variables:
          - group: 'AWS_ECR_Credentials'  # Ensure this group exists and is correctly populated
          - name: IMAGE_TAG
            value: $(Build.BuildId)  # This is the only variable defined here

        steps:
          - checkout: self

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo "Setting up AWS CLI..."
                echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
                echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
                echo "AWS_REGION: $AWS_REGION"
                aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
                aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
                aws configure set default.region $AWS_REGION
                aws sts get-caller-identity  # Verify credentials
            displayName: 'AWS CLI Setup and Verification'

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo "Logging in to Amazon ECR..."
                aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
            displayName: 'Login to AWS ECR'

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo "Building the Docker image..."
                docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
            displayName: 'Build Docker Image'

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo "Tagging the Docker image..."
                docker tag $ECR_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
            displayName: 'Tag Docker Image'

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo "Pushing the Docker image to AWS ECR..."
                docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
            displayName: 'Push Docker Image to ECR'

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo "Docker image successfully pushed to AWS ECR!"
            displayName: 'Success Message'
