trigger:
  branches:
    include:
      - main

variables:
  - group: AWS_ECR_Credentials  # Link to variable group containing AWS credentials

stages:
  - stage: BuildAndPush
    displayName: 'Build and Push Docker Image to AWS ECR'
    jobs:
      - job: Build
        displayName: 'Build and Push Job'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - checkout: self  # Checkout the source code

          - task: Bash@3
            displayName: 'AWS CLI Setup and Verification'
            inputs:
              targetType: 'inline'
              script: |
                echo "Setting up AWS CLI..."
                aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
                aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
                aws configure set default.region $(AWS_REGION)
                
                echo "Verifying AWS credentials..."
                aws sts get-caller-identity  # Validate credentials setup

          - task: Bash@3
            displayName: 'Login to AWS ECR'
            inputs:
              targetType: 'inline'
              script: |
                echo "Logging in to Amazon ECR..."
                aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com

          - task: Bash@3
            displayName: 'Build Docker Image'
            inputs:
              targetType: 'inline'
              script: |
                echo "Building the Docker image..."
                docker build -t $(ECR_REPOSITORY)/djapp:$(Build.BuildId) .

          - task: Bash@3
            displayName: 'Tag Docker Image'
            inputs:
              targetType: 'inline'
              script: |
                echo "Tagging the Docker image..."
                docker tag $(ECR_REPOSITORY)/djapp:$(Build.BuildId) $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(ECR_REPOSITORY)/djapp:$(Build.BuildId)

          - task: Bash@3
            displayName: 'Push Docker Image to ECR'
            inputs:
              targetType: 'inline'
              script: |
                echo "Pushing the Docker image to AWS ECR..."
                docker push $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(ECR_REPOSITORY)/djapp:$(Build.BuildId)

          - task: Bash@3
            displayName: 'Success Message'
            inputs:
              targetType: 'inline'
              script: |
                echo "Docker image successfully pushed to AWS ECR!"
